version: '2.2'

services:
  apt-cacher-ng:
    restart: always
    image: parchment/apt-cacher-ng:3.6.3-1
    init: true
    ports:
    - "3142:3142"
    volumes:
    - /srv/docker/apt-cacher-ng:/var/cache/apt-cacher-ng
